CREATE TABLE tour_packages (
    id VARCHAR(10) PRIMARY KEY,
    vehicle_type VARCHAR(50),
    no_of_days VARCHAR(20),
    no_of_persons VARCHAR(20),
    price DECIMAL(10,2),
    suggest_places TEXT
);

INSERT INTO tour_packages (id, vehicle_type, no_of_days, no_of_persons, price, suggest_places) VALUES
('1.01', 'Car', 'Three', '2-3', 425.00, 'Colombo-Sigiriya-Kandy'),
('1.02', 'Car', 'Four', '2-3', 475.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy'),
('1.03', 'Car', 'Five', '2-3', 525.00, 'Colombo - Benthota - Ella - Nuwaraeliya - Kandy OR Colombo - Sigiriya - Trincomalee - Kandy'),
('1.04', 'Car', 'Six', '2-3', 595.00, 'Colombo - Sigiriya - Kandy - NuwaraEliya - Ella - Galle OR Colombo - Sigiriya - Trincomalee - Kandy - Galle'),
('1.05', 'Car', 'Seven', '2-3', 625.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Galle OR Colombo - Sigiriya - Kandy - Nuwraeliya - Yala or Udawalawa - Mirissa - Benthota'),
('1.06', 'Car', 'Eight', '2-3', 675.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Kandy - Nuwara Eliya - Yala OR Udawalawe National Park - Galle'),
('1.07', 'Car', 'Nine', '2-3', 725.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.08', 'Car', 'Ten', '2-3', 775.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.09', 'Car', 'Eleven', '2-3', 825.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.10', 'Car', 'Twelve', '2-3', 875.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.11', 'Car', 'Thirteen', '2-3', 925.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.12', 'Car', 'Fourteen', '2-3', 975.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('1.13', 'Car', 'Fifteen', '2-3', 1025.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle');

INSERT INTO tour_packages (id, vehicle_type, no_of_days, no_of_persons, price, suggest_places) VALUES
('2.01', 'Mini Van', 'Three', '5-6', 455.00, 'Colombo-Sigiriya-Kandy'),
('2.02', 'Mini Van', 'Four', '5-6', 515.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy'),
('2.03', 'Mini Van', 'Five', '5-6', 575.00, 'Colombo - Benthota - Ella - Nuwaraeliya - Kandy OR Colombo - Sigiriya - Trincomalee - Kandy'),
('2.04', 'Mini Van', 'Six', '5-6', 635.00, 'Colombo - Sigiriya - Kandy - NuwaraEliya - Ella - Galle OR Colombo - Sigiriya - Trincomalee - Kandy - Galle'),
('2.05', 'Mini Van', 'Seven', '5-6', 695.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Galle OR Colombo - Sigiriya - Kandy - Nuwraeliya - Yala or Udawalawa - Mirissa - Benthota'),
('2.06', 'Mini Van', 'Eight', '5-6', 755.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Kandy - Nuwara Eliya - Yala OR Udawalawe National Park - Galle'),
('2.07', 'Mini Van', 'Nine', '5-6', 815.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.08', 'Mini Van', 'Ten', '5-6', 875.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.09', 'Mini Van', 'Eleven', '5-6', 935.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.10', 'Mini Van', 'Twelve', '5-6', 995.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.11', 'Mini Van', 'Thirteen', '5-6', 1055.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.12', 'Mini Van', 'Fourteen', '5-6', 1115.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('2.13', 'Mini Van', 'Fifteen', '5-6', 1175.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle');

INSERT INTO tour_packages (id, vehicle_type, no_of_days, no_of_persons, price, suggest_places) VALUES
('3.01', 'Large Van', 'Three', '9-10', 530.00, 'Colombo-Sigiriya-Kandy'),
('3.02', 'Large Van', 'Four', '9-10', 595.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy'),
('3.03', 'Large Van', 'Five', '9-10', 660.00, 'Colombo - Benthota - Ella - Nuwaraeliya - Kandy OR Colombo - Sigiriya - Trincomalee - Kandy'),
('3.04', 'Large Van', 'Six', '9-10', 725.00, 'Colombo - Sigiriya - Kandy - NuwaraEliya - Ella - Galle OR Colombo - Sigiriya - Trincomalee - Kandy - Galle'),
('3.05', 'Large Van', 'Seven', '9-10', 785.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Galle OR Colombo - Sigiriya - Kandy - Nuwraeliya - Yala or Udawalawa – Mirissa - Benthota'),
('3.06', 'Large Van', 'Eight', '9-10', 850.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Kandy - Nuwara Eliya - Yala OR Udawalawe National Park - Galle'),
('3.07', 'Large Van', 'Nine', '9-10', 915.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.08', 'Large Van', 'Ten', '9-10', 980.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.09', 'Large Van', 'Eleven', '9-10', 1045.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.10', 'Large Van', 'Twelve', '9-10', 1100.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.11', 'Large Van', 'Thirteen', '9-10', 1175.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.12', 'Large Van', 'Fourteen', '9-10', 1240.00, 'Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle , Mirissa - Galle - Hikkaduwa, Bentota OR Colombo - Wilpattu - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah , Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle'),
('3.13', 'Large Van', 'Fifteen', '9-10', 1305.00, 'Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Tangalle OR Mirissa - Galle OR Colombo - Sigiriya - Anuradhapura OR Polonnaruwa - Trincomalee - Pasikudah OR Arugam Bay - Kandy - Nuwara Eliya - Ella - Yala OR Udawalawe National Park - Galle');